[package]
name = "tokio-chat-app"
version = "0.1.0"
authors = ["Vitor Serigati"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = {version = "1", features = ["full"]}
